version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t civisanalytics/civis-jupyter-python2 .
      - run: docker run civisanalytics/civis-jupyter-python2 /bin/bash -c "echo BUILDS OK"
      - run: docker run civisanalytics/civis-jupyter-python2 python -c "import civis"
      - run: docker run civisanalytics/civis-jupyter-python2 python -c "from scipy.linalg import _fblas"
      - run: docker run civisanalytics/civis-jupyter-python2 python -c "import numpy, os; import matplotlib.pyplot as plt; x = numpy.arange(100); y = numpy.sin(x); plt.plot(x, y);"
      - run: docker run civisanalytics/civis-jupyter-python2 python -c "import seaborn"
      - run: docker run civisanalytics/civis-jupyter-python2 /bin/bash -c "python -c 'import numpy'"
      - run: docker run civisanalytics/civis-jupyter-python2 python -c "from numpy.distutils import system_info; assert system_info.get_info('mkl') == {}"
      - run: docker run civisanalytics/civis-jupyter-python2 python -c "import numpy; numpy.test()"
      - run: docker run civisanalytics/civis-jupyter-python2 /bin/bash -c "conda list|grep conda-forge"
